services:
  - type: web
    name: phantom-trace
    runtime: node
    buildCommand: npm install --prefix backend && node files/generate_files.js
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
